version: '3.8'

services:
  ui:
    image: hawkinsr/uidemo:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
        reservations:
          cpus: '0.1'
          memory: 20M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
      - target: 80
        published: 8080
        protocol: tcp

  api:
    image: hawkinsr/apidemo:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
        reservations:
          cpus: '0.1'
          memory: 20M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
      - target: 80
        published: 7262
        protocol: tcp
